namespace TownOfUs
{
    public enum CustomRPC
    {
        SetJester = 50,
        SetCouple,
        SetMayor,
        SetSheriff,
        SetEngineer,
        SetSwapper,
        SetShifter,
        SetInvestigator,
        SetTimeLord,
        SetMedic,
        SetSeer,
        SetMorphling,
        SetPoisoner,
        SetPuppeteer,
        SetCamouflager,
        SetExecutioner,
        SetTarget,
        SetSpy,
        SetSnitch,
        SetTracker,
        SetMiner,
        SetSwooper,
        SetJanitor,
        SetCannibal,
        SetArsonist,
        SetAltruist,
        SetUndertaker,
        SetAssassin,
        SetVigilante,
        SetChameleon,
        SetUnderdog,
        SetGrenadier,
        SetFramer,
        SetFreezer,

        
        SetBait,
        SetGiant,
        SetBlind,
        SetButtonBarry,
        SetChild,
        SetDiseased,
        SetDrunk,
        SetFlash,
        SetTiebreaker,
        SetTorch,
        SetVolatile,

        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetCrewmate,
        SetImpostor,


        LoveWin,
        GlitchWin,
        ArsonistWin,
        CannibalWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        ShifterLose,
        GlitchLose,
        ArsonistLose,
        CannibalLose,
        NobodyWins,
        PhantomLose,

        JanitorClean,
        CannibalEat,
        PoisonAlert,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Shift,
        Protect,
        AttemptSound,
        Investigate,
        Frame,
        Track,
        Rewind,
        RewindRevive,
        Morph,
        Camouflage,
        Mine,
        Swoop,
        ChameleonSwoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        FlashGrenade,

        SetGlitch,
        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,


        Start,
        SyncCustomSettings,
        FixAnimation,
        
        AddMayorVoteBank,
        Possess,
        UnPossess,
        PossessKill,
        Freeze,
    }
}
